[workspace]
members = [
    "node/Original-Node",
    "pallets/template",
    "pallets/collectibles",
    "pallets/kitties",
    "pallets/ea4healthcare",
    "runtime/Original-Runtime",
]
[profile.release]
panic = "unwind"
